
#define VERTEX_POSITION     layout( location = 0 ) in vec3
#define VERTEX_NORMAL       layout( location = 1 ) in vec3
#define VERTEX_TANGENT      layout( location = 2 ) in vec3
#define VERTEX_BINORMAL     layout( location = 3 ) in vec3
#define VERTEX_COLOR        layout( location = 4 ) in vec3
#define VERTEX_TEXCOORD0    layout( location = 5 ) in vec2
#define VERTEX_TEXCOORD1    layout( location = 6 ) in vec2
